server:
  port: 8000
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,application/javascript,application/x-javascript,text/css,application/xml,application/json
    min-response-size: 1024
mybatis:
  mapper-locations:
    - classpath*:com/bestfeng/boot/**/mapper/dao/*.xml

jwt:
  tokenHeader: fw-access-token #JWT存储的请求头
  secret: fw-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  #tokenHead: Bearer  #JWT负载中拿到开头
secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /druid/**
      - /actuator/**
      - /sso/**
      - /authentication/**
      - /**
spring:
  profiles:
    active: prod
  application:
    name: dydj
  resources:
    static-locations: file:./ui/,file:./static/,/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/resources/,classpath:/static/, classpath:/ui/
  redis:
    database: 1
    host: 47.108.196.40
    password: ''
    port: 6379
    timeout: 3000ms
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接