spring:
  datasource:
    url: jdbc:mysql://47.108.133.178:3360/we7?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: abc.123

logging:
  level:
    com.bestfeng.dydj.*: debug
    org.springframework: warn
    org.aurochsframework.boot.*: debug
    log4j.logger.com.ibatis: debug
    #system: debug


