spring:
  datasource:
    url: jdbc:mysql://rm-uf686an1j5gkw1886ao.mysql.rds.aliyuncs.com/uni?zeroDateTimeBehavior=convertToNull
    username: 'testuni'
    password: '!QAZ2wsx3edc'

logging:
  level:
    com.bestfeng.dydj.*: debug
    org.springframework: warn
    org.aurochsframework.boot.*: debug
    log4j.logger.com.ibatis: debug
    #system: debug
wechat:
  appId: 'wx3a064f24347b34d2'
  appSecret: '2fe25c657f2c7ab751e09f249c04b7c7'

